// Central enemy balance config.
// Tune these values to adjust game difficulty quickly.
export const ENEMY_STATS = {
  abyss_wolf_pack: {
    name: 'Abyss Wolf Pack',
    hp: 28,
    ac: 1,
    attack: 4,
    damage: '1d2+2',
    xp: 90,
    gold: 20,
  },
  elite_blackguard: {
    name: 'Elite Blackguard',
    hp: 42,
    ac: 5,
    attack: 6,
    damage: '1d6+3',
    xp: 170,
    gold: 45,
  },
  abyss_lord: {
    name: 'Abyss Lord',
    hp: 57,
    ac: 8,
    attack: 8,
    damage: '1d8+4',
    xp: 300,
    gold: 120,
  },
  dungeon_guard: {
    name: 'Dungeon Guard',
    hp: 30,
    ac: 4,
    attack: 4,
    damage: '1d6+2',
    xp: 50,
    gold: 15,
  },
  dungeon_guards_pair: {
    name: 'Dungeon Guards',
    hp: 44,
    ac: 7,
    attack: 4,
    damage: '1d6+2',
    xp: 100,
    gold: 30,
  },
  giant_rat: {
    name: 'Giant Rat',
    hp: 7,
    ac: 1,
    attack: 2,
    damage: '1d4+1',
    xp: 25,
    gold: 0,
  },
  skeleton: {
    name: 'Skeleton',
    hp: 13,
    ac: 2,
    attack: 4,
    damage: '1d6+2',
    xp: 50,
    gold: 5,
  },
}
